### Lagoon Drupal 8 production environment services file.
#
# This file should contain service definitions that are needed on production environments
#
# It contains some defaults that the Lagoon team suggests, please edit them as required.
#
parameters:
  twig.config: # disabling twig debugging and auto reload, plus enabling twig caching
    debug: false
    auto_reload: null
    cache: true