docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    - run:
        name: env variables
        command: env
        service: cli
        
    - run:
        name: IF no Drupal installed & Pullrequest = Sync database from dev
        command: |
            if [[ -n ${LAGOON_PR_BASE_BRANCH} ]] && ! drush status --fields=bootstrap | grep -q "Successful"; then
                drush -y sql-sync @master default
            fi
        service: cli

    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cim
        command: drush -y cim
        service: cli

environments:
  master:
    cronjobs:
      - name: drush cron
        schedule: "H * * * *"
        command: drush cron
        service: cli
    routes:
      - varnish:
          - "contribkanban.com"