current: amazeeio
docker-compose-yaml: docker-compose.yml
environment_variables:
  git_sha: "true"
environments:
  main:
    cronjobs:
    - command: drush cron
      name: drush cron
      schedule: H * * * *
      service: cli
    routes:
    - frontend:
      - app.contribkanban.com:
          insecure: Redirect
          tls-acme: "true"
      - contribkanban.com:
          insecure: Redirect
          tls-acme: "true"
      - www.contribkanban.com:
          insecure: Redirect
          tls-acme: "true"
    - nginx:
      - api.contribkanban.com:
          insecure: Redirect
          tls-acme: "true"
project: contribkanban
routes:
  insecure: Redirect
tasks:
  post-rollout:
  - run:
      command: |
        if [[ -n ${LAGOON_PR_BASE_BRANCH} ]] && ! drush status --fields=bootstrap | grep -q "Successful"; then
            ./bin/drush -y site-install --account-pass=admin
        fi
      name: If this is a pull request, install the database.
      service: cli
  - run:
      command: ./bin/drush updb --yes
      name: drush updb
      service: cli
  - run:
      command: ./bin/drush cim --yes
      name: drush cim
      service: cli
  - run:
      command: ./bin/drush sapi-i --yes
      name: drush sapi-i
      service: cli
  - run:
      command: ./scripts/github-build-status.sh success
      name: Push a pending status
      service: cli
  pre-rollout:
  - run:
      command: env
      name: env variables
      service: cli
