docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    - run:
        name: If this is a pull request, install the database.
        command: |
            if [[ -n ${LAGOON_PR_BASE_BRANCH} ]] && ! drush status --fields=bootstrap | grep -q "Successful"; then
                ./bin/drush -y site-install --account-pass=admin
            fi
        service: cli

    - run:
        name: drush updb
        command: ./bin/robo deploy
        service: cli

environments:
  master:
    cronjobs:
      - name: drush cron
        schedule: "H * * * *"
        command: drush cron
        service: cli
    routes:
      - nginx:
        - contribkanban.com:
            tls-acme: 'false'
            insecure: Allow
        - www.contribkanban.com:
            tls-acme: 'false'
            insecure: Allow
