current: amazeeio
docker-compose-yaml: docker-compose.yml
environment_variables:
  git_sha: "true"
environments:
  master:
    cronjobs:
    - command: drush cron
      name: drush cron
      schedule: H * * * *
      service: cli
    routes:
    - frontend:
      - app.contribkanban.com:
          insecure: Redirect
          tls-acme: "true"
      - contribkanban.com:
          insecure: Redirect
          tls-acme: "true"
      - www.contribkanban.com:
          insecure: Redirect
          tls-acme: "true"
    - nginx:
      - api.contribkanban.com:
          insecure: Redirect
          tls-acme: "true"
project: contribkanban
routes:
  insecure: Redirect
tasks:
  post-rollout:
  - run:
      command: |
        if [[ -n ${LAGOON_PR_BASE_BRANCH} ]] && tables=$(drush sqlq 'show tables;') && [ -z "$tables" ]; then
            php bin/drush -y site-install --account-pass=admin
        fi
      name: If this is a pull request, install the database.
      service: cli
  - run:
      command: php bin/drush updb --yes
      name: drush updb
      service: cli
  - run:
      command: php bin/drush cim --yes
      name: drush cim
      service: cli
  - run:
      command: php bin/drush sapi-i --yes
      name: drush sapi-i
      service: cli
  - run:
      command: ./scripts/github-build-status.sh success
      name: Push a pending status
      service: cli
  pre-rollout:
  - run:
      command: env
      name: env variables
      service: cli
  # - run:
  #     command: ./scripts/github-build-status.sh pending
  #     name: Push a pending status
  #     service: cli
