name: frontend
type: nodejs:4.2

web:
  commands:
    start: "NODE_ENV=production npm start &>> logs/app.log"
  locations:
    "/app":
      passthru: false
      root: "app"
      allow: true
      expires: 1d
      rules:
        '\.png$':
          allow: true
          expires: -1
        '\.svg$':
          allow: true
          expires: -1
disk: 512
relationships:
    database: "mongodb:mongodb"
hooks:
  build: |
    set -e
    gem install sass
    bower install -p
    grunt sass
#  This is perpetually throwing rate limit error.
#  deploy: |
#    grunt clear-cache
dependencies:
#  ruby:
#    sass: "3.4.7"
  nodejs:
      grunt-cli: "~0.1.13"
      bower: "~1.3.3"
mounts:
  "/logs": "shared:files/logs"
