<?php declare(strict_types=1);

use Drupal\consumers\Entity\Consumer;
use Drupal\Core\Entity\EntityRepositoryInterface;

function contribkanban_api_ensure_default_consumer() {
    $entity_repository = \Drupal::service('entity.repository');
    assert($entity_repository instanceof EntityRepositoryInterface);

    $exists = $entity_repository->loadEntityByUuid('consumer', 'd4f7c501-cff9-4a3f-bae7-aec1db19456c');
    if ($exists === null) {
        $consumer = Consumer::create([
            'uuid' => 'd4f7c501-cff9-4a3f-bae7-aec1db19456c',
            'owner_id' => '',
            'label' => 'Frontend',
            'is_default' => TRUE,
            'secret' => user_password(),
            'confidential' => FALSE,
            'third_party' => FALSE,
            'roles' => [['target_id' => 'frontend']],
        ]);
        $consumer->save();
    }
}

/**
 * Implements hook_modules_installed().
 */
function contribkanban_api_modules_installed($modules) {
    if (in_array('consumers', $modules)) {
        $initial_consumer = Consumer::load(1);
        if ($initial_consumer) {
            $initial_consumer->delete();
        }
        contribkanban_api_ensure_default_consumer();
    }
}
