<?php

/**
 * Implements hook_entity_type_build().
 */
function contribkanban_api_entity_type_build(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  $entities_marked_internal = [
    'block', 'field_config', 'field_storage_config', 'filter_format',
    'view', 'base_field_override', 'entity_view_mode', 'entity_view_display',
    'entity_form_mode', 'date_format', 'user_role', 'entity_form_display',
    'menu', 'action', 'rest_resource_config', 'page', 'page_variant', 'node_type',
    'node',
  ];
  foreach ($entities_marked_internal as $entity_type_id) {
    if (isset($entity_types[$entity_type_id])) {
      $entity_types[$entity_type_id]->set('internal', TRUE);
    }
  }
}
