<?php

/**
 * @file
 * Module file for contribkanban_boards.
 */

use Drupal\contribkanban_boards\FieldHelper;
use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function contribkanban_boards_theme($existing, $type, $theme, $path) {
  return [
    'board' => [
      'render element' => 'elements',
    ],
    'board_list' => [
      'render element' => 'elements',
    ],
    'field__board__lists' => [
      'base hook' => 'field',
    ],
    'board_form' => [
      'render element' => 'form',
    ],
    'board_list_form' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function contribkanban_boards_preprocess_board(&$variables) {
  $variables['board'] = [];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['board'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function contribkanban_boards_preprocess_board_list(&$variables) {
  $variables['#attached']['library'][] = 'contribkanban_boards/board_list';
  /** @var \Drupal\contribkanban_boards\Entity\BoardListInterface $board_list */
  $board_list = $variables['elements']['#board_list'];
  $variables['title'] = ['#markup' => $board_list->label()];
  $attributes =& $variables['attributes'];
  $attributes['data-drupal-selector'] = 'board-list';
  $attributes['data-projects'] = FieldHelper::stringAsJson($board_list->getProjects());
  $attributes['data-category'] = FieldHelper::stringAsJson($board_list->getCategory());
  $attributes['data-component'] = FieldHelper::stringAsJson($board_list->getComponent());
  $attributes['data-parent'] = FieldHelper::stringAsJson($board_list->getParentIssue());
  $attributes['data-priority'] = FieldHelper::stringAsJson($board_list->getPriority());
  $attributes['data-statuses'] = FieldHelper::stringAsJson($board_list->getStatuses());
  $attributes['data-tag'] = FieldHelper::stringAsJson($board_list->getTags());
  $attributes['data-version'] = FieldHelper::stringAsJson($board_list->getVersion());
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function contribkanban_boards_inline_entity_form_entity_form_alter(&$entity_form, &$form_state) {
  if ($entity_form['#entity_type'] == 'board_list') {
    $entity_form['#theme'] = ['board_list_form'];
    $entity_form['#attached']['library'][] = 'contribkanban_boards/form';
  }
}
