FROM amazeeio/php:8.3-cli-drupal:latest

RUN composer self-update --2

COPY composer.json composer.lock /app/
COPY scripts /app/scripts
# Uncomment if you have a patches directory in your Drupal Installation
# COPY patches /app/patches
RUN composer install --prefer-dist --no-dev
COPY . /app

ENV WEBROOT=web
